name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your default branch name if it's not 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install # Modify this if you're using a different package manager

      - name: Build Project
        run: npm run build # Modify this command for your build setup

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
